title: CompuCell3D
description: Multiscale modeling framework

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

#theme: minima

url: https://compucell3d.org
baseurl: ""

#plugins:
#  - jekyll-feed